[alias]
scaffold = "run --bin scaffold --quiet --release -- "
download = "run --bin download --quiet --release -- "
read = "run --bin read --quiet --release -- "

solve = "run --bin solve --quiet --release -- "
all = "run"
time = "run --release -- --time"

[env]
AOC_YEAR = "2022"
